apiVersion: v1
kind: Service
metadata:
  name: business-tools-api
  labels:
    app.kubernetes.io/name: business-tools-api
    app.kubernetes.io/part-of: business-tools
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: business-tools-api
  ports:
    - name: http
      port: 8000
      targetPort: http
