apiVersion: v1
kind: Service
metadata:
  name: business-tools-oauth2-proxy
  labels:
    app.kubernetes.io/name: business-tools-oauth2-proxy
    app.kubernetes.io/part-of: business-tools
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: business-tools-oauth2-proxy
  ports:
    - name: http
      port: 4180
      targetPort: http
