apiVersion: v1
kind: Service
metadata:
  name: business-tools-web
  labels:
    app.kubernetes.io/name: business-tools-web
    app.kubernetes.io/part-of: business-tools
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: business-tools-web
  ports:
    - name: http
      port: 80
      targetPort: http
