apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: business-tools-api-secrets
  namespace: business-tools
spec:
  organizationId: "a61dae02-b8f9-4023-8e20-b4c300b91f60"
  secretName: business-tools-api-secret
  onlyMappedSecrets: true
  map:
    - bwSecretId: cfada61e-eccc-4cbe-824b-b4c300c794d0
      secretKeyName: ECWID_API_TOKEN
    - bwSecretId: 3e86e352-ca1a-4381-a17e-b4c300c7c7af
      secretKeyName: ECWID_SHOP_ID
  authToken:
    secretName: bw-auth-token
    secretKey: token
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: business-tools-auth-secrets
  namespace: business-tools
spec:
  organizationId: "a61dae02-b8f9-4023-8e20-b4c300b91f60"
  secretName: business-tools-auth-secret
  onlyMappedSecrets: true
  map:
    - bwSecretId: d585cbea-0734-4582-9b5a-b4c300c7fbab
      secretKeyName: OIDC_ISSUER_URL
    - bwSecretId: 12ddcb3c-b498-467f-8a6a-b4c300c8bb50
      secretKeyName: OAUTH2_PROXY_CLIENT_ID
    - bwSecretId: ea7285fa-2f84-45fa-89c3-b4c300c92d1a
      secretKeyName: OAUTH2_PROXY_CLIENT_SECRET
    - bwSecretId: 3fa9fd05-74c2-4f5e-98e5-b4c300c96cfe
      secretKeyName: OAUTH2_PROXY_COOKIE_SECRET
  authToken:
    secretName: bw-auth-token
    secretKey: token
