apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - oauth2-proxy-ingress.yaml

images:
  - name: ghcr.io/example/business-tools-api
    newName: ghcr.io/kengaul/business-tools-api
    newTag: latest
  - name: ghcr.io/example/business-tools-web
    newName: ghcr.io/kengaul/business-tools-web
    newTag: latest
