apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: business-tools-oauth2-proxy
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - macmini.localdomain
      secretName: business-tools-tls
  rules:
    - host: macmini.localdomain
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: business-tools-oauth2-proxy
                port:
                  name: http

